# Generated by Django 5.1.6 on 2025-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_student_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_employer",
            field=models.BooleanField(default=False),
        ),
    ]
