# Generated by Django 5.1.6 on 2025-02-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_student_is_employer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="is_employer",
        ),
    ]
